image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: /bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/moaible/be368018805ab6d667524c404c14fdfe/raw/be65ff7256a873041e198adf7304342a0cebee94/aws_ssh.sh)"
